#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar--
# Default Config:
# ~/.config/polybar/config
  polybar  head &
# polybar  tail &
  polybar  hdmi &
  polybar  tailback &
  polybar  tailleft &
  polybar  tailcenter &
  polybar  tailright &
echo "Polybars Populated!"
